### ISSUE TITLE
Not working with PHP 7.2

### ISSUE THREAD

**Issue by Waldemar-Denke** [opengento/magento2-gdpr#10]
Magento 2.3 PHP 7.2.14

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - opengento/module-gdpr dev-magento2.3.x requires magento/framework ^101.0.7 -> satisfiable by magento/framework[101.0.7].
    - Installation request for opengento/module-gdpr dev-magento2.3.x -> satisfiable by opengento/module-gdpr[dev-magento2.3.x].
Installation failed, reverting ./composer.json to its original content.

**Comment by Waldemar-Denke** [comment]
Hi @thomas-blackbird, yes it seems to work now. I did some changes in composer.json. php version and all magento versions. See my fork.

**Comment by thomas-kl1** [comment]
Is fixed in version 3.0.0-beta
