### ISSUE TITLE
[BUG] Some config fields are not displayed on a store scope (Magento 2.4.2)

### ISSUE THREAD

**Issue by owebia** [opengento/magento2-gdpr#100]
## Description  
Some config fields are not displayed on a store scope (Magento 2.4.2).

They display well on the global scope.

## Prerequisites  

**PHP Version:**
 - 7.4.20

**Magento Version:**
 - 2.4.2

**Module Version:**
 - 4.1.3

**Desktop (if applicable):**  
- OS: Windows
- Browser chrome
- Version 91.0.4472.114

## Issue Details  

**Steps to reproduce the behavior**
1. Go to 'Stores' -> 'Configuration' -> 'GDPR Compliance' -> 'Data Erasure'
2. Change the scope to store view (2 stores in my Magento instance)
3. Some fields (e.g. 'Right To Erasure' -> 'Information') should be displayed

**Expected behavior**  
All store scope fields should be displayed when setting configuration at store level.

**Screenshots**  
![Configuration-Settings-Stores-Magento-Admin (1)](https://user-images.githubusercontent.com/604741/124309378-ea5e5880-db6a-11eb-9763-878a4640b3f4.png)

**Additional context**  
Magento instance with multiple stores configured.  
Each store should be able to set it's own configuration (e.g. information blocks).

Seems to be a Magento issue, similar to https://github.com/magento/magento2/issues/767

**Comment by thomas-kl1** [comment]
@owebia Hi, I can't reproduce this issue, could you give more detailed steps?
I've been on the Data Erasure tab, and I've been on a store view (I do have multiple websites and store views). I can see all fields that are available for the store view scope.

**Comment by owebia** [comment]
@thomas-kl1 thanks, I will have a look in the week

**Comment by owebia** [comment]
Here is what I do to reproduce the issue (I use swissup/module-search-mysql-legacy to avoid the dependency to elasticsearch):
```
composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.4.2 /path/to/install --no-install
composer require --no-update opengento/module-gdpr
composer install
bin/magento setup:install --admin-firstname=firstname  --admin-lastname=lastname  --admin-email='email@example.com'  --admin-user=admin  --admin-password=admin  --base-url='https://store.url/'  --backend-frontname=admin  --db-host=localhost  --db-name=magento  --db-user=magento  --db-password=magento  --cleanup-database  --disable-modules='Magento_Elasticsearch7,Magento_Elasticsearch6,Magento_Elasticsearch'
composer config repositories.swissup composer https://docs.swissuplabs.com/packages/
composer require swissup/module-search-mysql-legacy --prefer-source --ignore-platform-reqs
bin/magento module:enable Swissup_SearchMysqlLegacy Swissup_Core
# Disable Magento_TwoFactorAuth for dev
bin/magento module:disable Magento_TwoFactorAuth
bin/magento setup:upgrade
bin/magento setup:di:compile
```

Then:
1. Connect to backoffice
2. Go to 'Stores' > 'Configuration' > 'GDPR Compliance' > 'Global'
3. Set 'General' > 'Enabled' to 'Yes, save
4. Go to 'GDPR Compliance' > 'Data Erasure'
5. Select Scope = Default Store View
6. Some fields/titles/fieldsets are not displayed
