### ISSUE TITLE
[BUG] Composer opengento/module-gdpr : Require Command Install Failure Magento 2.3.7

### ISSUE THREAD

**Issue by ajc200x** [opengento/magento2-gdpr#106]
## Description  
 Problem 1
    - opengento/module-gdpr[4.1.0, ..., 4.1.3] require magento/framework ^103.0 -> found magento/framework[103.0.0, ..., 103.0.2-p1] but the package is fixed to 102.0.7 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires opengento/module-gdpr ^4.1 -> satisfiable by opengento/module-gdpr[4.1.0, 4.1.1, 4.1.2, 4.1.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

## Prerequisites  
Follow Instructions... 
composer require opengento/module-gdpr
**PHP Version:**
PHP 7.4

**Magento Version:**
M2.3.7 CE

**Module Version:**
opengento/module-gdpr [4.1.0, ..., 4.1.3] 

**Expected behavior**  
Successful Install of GDPR Module.

**Comment by thomas-kl1** [comment]
Hi @ajc200x ,

The composer installation fails because you try to require ^2.4 on a Magento version of 2.3.x, which is not supported in 4.x versions of the GDPR module.
I'm going to backport 4.x modification in the 3.x versions. This ticket will be updated when available. (Maybe this week)

**Comment by thomas-kl1** [comment]
Won't do, we are going to focus on Magento 2.4 now. Sorry for the pain!
