### ISSUE TITLE
[BUG] The "last_visit_at" attribute name is invalid. Reset the name and try again.

### ISSUE THREAD

**Issue by Quazz** [opengento/magento2-gdpr#107]
## Description  
When cron task gdp_erase_entity_scheduler runs, an error is logged in system.log

## Prerequisites  

**PHP Version:**
 - 7.4

**Magento Version:**
 - 2.4.2

**Module Version:**
 - 4.1.3

## Issue Details  

**Steps to reproduce the behavior**
1. Wait for cron task gdp_erase_entity_scheduler to run 
2. Observe system.log

**Expected behavior**  
1. No error logged and cron task finishes succesfully

**Comment by Quazz** [comment]
I looked into it a little bit and it seems like

https://github.com/opengento/magento2-gdpr/blob/magento2.4.x/Model/Customer/SourceProvider/FilterModifier.php

That file has some issues in it at the very least. 

For example https://github.com/opengento/magento2-gdpr/blob/magento2.4.x/Model/Customer/SourceProvider/FilterModifier.php#L33 I think it is trying to join on the wrong table (cl instead of cv)

https://github.com/opengento/magento2-gdpr/blob/magento2.4.x/Model/Customer/SourceProvider/FilterModifier.php#L26

This select selects the customer_id and last_visit_at column twice. When a select query is started like this using from(), it by default selects every column, when you then specify columns through columns() it adds them on top of that which is invalid SQL. (to fix, pass second parameter 'customer_id' column name to from() and remove it from columns()) 

It also expects 'main_table' to be specified, but this cron task defines it main table as 'e'.  (couldn't find exactly where that happens, might be default magento behavior)

https://github.com/opengento/magento2-gdpr/blob/magento2.4.x/Cron/EraseEntityScheduler.php#L94

It's passing a datetime object

But even when you fix all that, it still throws this error. 

I think it tries to add the filter to the initial query (customer_entity table), but it doesn't contain the column.

**Comment by thomas-kl1** [comment]
Hi @Quazz ! Thanks for reporting this issue. What exception do you face in the logs?

**Comment by Quazz** [comment]
> Hi @Quazz ! Thanks for reporting this issue. What exception do you face in the logs?

main.ERROR: The "last_visit_at " attribute name is invalid. Reset the name and try again.
