### ISSUE TITLE
[BUG] Attempts to unsubscribe anonymized email

### ISSUE THREAD

**Issue by Quazz** [opengento/magento2-gdpr#109]
## Description  
The subscribed email addresses are anonymized before they are attempted to be unsubscribed resulting in undelivered emails

## Prerequisites  

**PHP Version:**
 - 7.4

**Magento Version:**
 - 2.4.3

**Module Version:**
 - 4.1.5

## Issue Details  

**Steps to reproduce the behavior**
Not 100% sure. 

Don't know if it's strictly the the newsletter subscriptions or if it's customer anonymization into attempting to unsubscribe, but having those by up for erasing/anonymization

You end up getting emails about the mail not being delivered to email addresses such as 'vbe-anonymous-rp@gdpr.org' (and similar)

**Expected behavior**  
Clean unsubscription on the original email address, anonymize it after

**Comment by thomas-kl1** [comment]
Pending release
