### ISSUE TITLE
Cookie Popin doesn't appear

### ISSUE THREAD

**Issue by thibelad** [opengento/magento2-gdpr#11]
> Magento 2.3.1
> PHP 7.2.14
> Download ZIP master of your module.

Hello,

I don't have any popin for cookies. I added the CMS block with `id` equal to `cookies-policy` but I have nothing.
Do you know why ?

Many thanks for your feedback.

**Comment by thomas-kl1** [comment]
Hi @thibelad 

I've been able to reproduce the issue. I'll try to fix it as soon as possible.

**Comment by thomas-kl1** [comment]
Will be released within the next version.
