### ISSUE TITLE
[BUG] Compilation error: PHP Fatal error:  Interceptor may not inherit from final class (Opengento\Gdpr\Block\Adminhtml\Customer\Edit\EraseButton)

### ISSUE THREAD

**Issue by magentoguru** [opengento/magento2-gdpr#110]
## Prerequisites  

**PHP Version:**
 - 7.2.0

**Magento Version:**
 - 2.3.6

**Module Version:**
 - 3.0.0

**Desktop (if applicable):**  
 - OS: Linux(Ubuntu)

## Issue Details  

**Steps to reproduce the behavior**
bin/magento setup:di:compile will give error:

PHP Fatal error:  Class Opengento\Gdpr\Block\Adminhtml\Customer\Edit\EraseButton\Interceptor may not inherit from final class (Opengento\Gdpr\Block\Adminhtml\Customer\Edit\EraseButton) in /var/www/html/generated/code/Opengento/Gdpr/Block/Adminhtml/Customer/Edit/EraseButton/Interceptor.php on line 7

**Expected behavior**  
Compilation should not give any error

**Screenshots**  

![Screenshot 2021-09-16 at 6 41 28 PM](https://user-images.githubusercontent.com/2987181/133716880-8e06222d-9d91-417a-942e-37253197271e.png)

**Comment by thomas-kl1** [comment]
Hi @magentoguru 

By curiosity, do you know what plugin is hooked to the ButtonProviderInterface?

**Comment by magentoguru** [comment]
Thanks for your reply. i dont think there is any plugin that is hooking ButtonProviderInterface

**Comment by magentoguru** [comment]
as amasty module have plugin hooking ButtonProviderInterface, just removing final keyword can fix this issue? thanks

**Comment by thomas-kl1** [comment]
Yes it will, I'm surprised they need to add plugin on this interface and not on a specific class. I'm curious what they are trying to achieve, I'll merge your MR asap

**Comment by magentoguru** [comment]
Thanks so much :) just for your information, i just shared image to explain the usage of plugin, thanks again

![Screenshot 2021-09-17 at 7 16 50 PM](https://user-images.githubusercontent.com/2987181/133774083-866a65ae-9fd3-457a-a611-4500c4bcccbe.png)

**Comment by thomas-kl1** [comment]
That's sad they should have declared the plugin over concrete class :/

**Comment by thomas-kl1** [comment]
@magentoguru Do you want to fix it on master also?

**Comment by magentoguru** [comment]
Yes please do on the master as well thanks

**Comment by magentoguru** [comment]
please let me know one it is merged to master, thanks so much :)

**Comment by magentoguru** [comment]
issue is fixed in 3.0.1, thanks thomas-kl1
