### ISSUE TITLE
[BUG] Fatal error: Uncaught TypeError: Argument 1 passed to Opengento\Gdpr\Service\Export\Processor\AbstractDataProcessor::collectData() 

### ISSUE THREAD

**Issue by magentoguru** [opengento/magento2-gdpr#112]
## Description  
Error 

## Prerequisites  

**PHP Version:**
 - 7.2.19

**Magento Version:**
 - 2.3.6

**Module Version:**
 - 3.0.1

## Issue Details  

**Steps to reproduce the behavior**
1. Go to Magento Backend
2. Click on  open Customers grid
3. Edit customer page
4. Click on "Export Personal Data" 

**Expected behavior**  
It should export customers data

**Screenshots**  

![Screenshot 2021-09-21 at 11 47 06 AM](https://user-images.githubusercontent.com/2987181/134108966-ff31cb0f-06c3-47f5-af5b-14c55c5d784b.png)

**Comment by magentoguru** [comment]
Hi  thomas-kl1,
i am getting same error when trying to login customer account.
Looking forward to hearing from you.
Thanks

**Comment by thomas-kl1** [comment]
Hi @magentoguru I'll take care of it tomorrow! I forget to backport some fix from the 4.x to the 3.x

**Comment by thomas-kl1** [comment]
Should be fixed in 3.0.2

**Comment by magentoguru** [comment]
thanks so much, i will check tomorrow. thanks again
