### ISSUE TITLE
[BUG] Download profile not working in magento admin

### ISSUE THREAD

**Issue by riwanmushtaq** [opengento/magento2-gdpr#113]
## Description  
on customer edit page in magento admin, ""

## Prerequisites  

**PHP Version:**
 -7.2.0

**Magento Version:**
 - 2.3.6

**Module Version:**
 - 3.0.1

## Issue Details  

**Steps to reproduce the behavior**
1. Go to  Customer grid in magento admin
2. Open customer edit page by clicking any customer grid "Edit" button
3. Export profile
4. No data is exported and button are no more showing, 

**Expected behavior**  
   Download  exported file

**Screenshots**  
https://www.awesomescreenshot.com/image/13831561?key=e95c77da763fb3531be52650c96db808

**Comment by magentoguru** [comment]
Hi @thomas-kl1 please let me know about this ticket. is it already done? or how do you see to start on it? will it be quick or how long it will take? thanks a lot :)

**Comment by thomas-kl1** [comment]
Hi @magentoguru  sorry for the lates answer..
It seems tha those issues were already fixed in 4.x, SO I need to backport the changes to 3.x, I don't have any ETA yet

**Comment by magentoguru** [comment]
Ok, thanks and looking forward to hearing

**Comment by magentoguru** [comment]
Hi @thomas-kl1 
it will be great if we have any progress on this

thanks in advance

**Comment by thomas-kl1** [comment]
Won't do, we are going to focus on Magento 2.4 now. Sorry for the pain!
