### ISSUE TITLE
[BUG] Profile file not downloaded on customer edit page

### ISSUE THREAD

**Issue by riwanmushtaq** [opengento/magento2-gdpr#114]
## Description  
On customer edit page, profile is not exported
## Prerequisites  

**PHP Version:**
 - 7.2.19

**Magento Version:**
 - 2.3.6

**Module Version:**
 - 3.0.2

## Issue Details  

**Steps to reproduce the behavior**
1. Login customer account
2. On customer edit page, click  "Privacy Settings"  tab
3. Click Export personal data button
4. No file exported

**Expected behavior**  
  It should download zip folder

**Screenshots**  
https://www.awesomescreenshot.com/image/13831561?key=e95c77da763fb3531be52650c96db808

**Comment by thomas-kl1** [comment]
Won't do, we are going to focus on Magento 2.4 now. Sorry for the pain!
