### ISSUE TITLE
[BUG] Guest users cannot download their own data

### ISSUE THREAD

**Issue by AmmarChishtiRP** [opengento/magento2-gdpr#115]
## Description  
Guest users cannot export their data because improper entity_id is being recorded in the "opengento_gdpr_export_entity" table

## Prerequisites  

**PHP Version:**
 - 7.4

**Magento Version:**
 - 2.4.3

**Module Version:**
 - [e.g. 1.0.0]

**Desktop (if applicable):**  
 - OS: macOS
 - Browser: Chrome
 - Version 94.0.4606.71

## Issue Details  

**Steps to reproduce the behavior**
1. Submit an order
2. Go to guest order view (<website-url>/sales/guest/form and fill in form info)
3. Click "Export Personal Data". You will see the message "A document is already available in your order page" however there is no way to download the document [1]
4. If you go to the "opengento_gdpr_export_entity" and search for the export entity that was just created, you will see that the entity_id is 0 but it should be the entity_id of the sales_order being viewed [2]

**Expected behavior**  
1. The guest should be able to click "Download Personal Data" and download the appropriate zip file [3]
2. I believe the solution is to set "getCustomerId()" in this line to "getId()" in https://github.com/opengento/magento2-gdpr/blob/5689c57ebd931bcf14ece95538252505f3179109/Controller/Guest/Export.php#L66 because guest orders have no customerId.

**Screenshots**  
[1] 
![image](https://user-images.githubusercontent.com/86006117/136859490-ddd040c4-1192-43a6-a1fc-23bc31d312e5.png)

[2]
![image](https://user-images.githubusercontent.com/86006117/136859511-89631c5e-071a-45a5-939b-482af410f9d3.png)

[3]
![image](https://user-images.githubusercontent.com/86006117/136859789-f4e670de-9dae-4f02-b726-4efd8d7b4197.png)

**Comment by thomas-kl1** [comment]
Pending release
