### ISSUE TITLE
[BUG] cant config page for cookie read more

### ISSUE THREAD

**Issue by dobak** [opengento/magento2-gdpr#117]
Hello,
thank you for your work, its great module!

We have problem with Read more Link on Cookies Popup

I sugest to change this line

20  //  private const CONFIG_PATH_GENERAL_INFORMATION_PAGE = 'gdpr/general/page_id';
    private const CONFIG_PATH_GENERAL_INFORMATION_PAGE = 'opengento_gdpr_general/general/page_id';

 in Model/PrivacyMessages.php

or please  create additional dropdown on the Cookies Policy config page for this value

**Comment by thomas-kl1** [comment]
Pending release
