### ISSUE TITLE
Export / Delete / Anonymize - Customer Guest Data

### ISSUE THREAD

**Issue by SomeGeek** [opengento/magento2-gdpr#12]
Provide a easy way for store owners to delete data from orders placed without account (guest checkout). Currently there seems to be no (easy) to do so.

A way to let customers do it themselves is by providing a way using their email address, send them a mail with a link to delete the data. That way no intervention from the store owner would be required. Maybe put in a threshold as some data need to be kept for a specified time for tax purposes.

**Comment by thomas-kl1** [comment]
Thanks @SomeGeek for the proposal!

I think we wan go further and allows the guest customer to export its personal data too.
It couldn't take long to implement the backend operations, however I'm open to suggestion for the frontend integration.

**Comment by SomeGeek** [comment]
Great, thanks for picking this up!

Other suggestions (maybe not directly related):

- [ ] Make the tools available in the admin sections, for novice users or to provide direct support for requests by phone (and yes, there are a lot of people who request things by phone even after placing an order online)
- [ ] Make it possible to create a guest order in the admin section. Right now, a customer profile has to be created before a order can be placed.

**Comment by thomas-kl1** [comment]
The first suggestion makes totally sens to me, however the second one is, to my point of view, not related to the scope of this module.
Actually it's a must have and it should be developed as a new module.

**Comment by SomeGeek** [comment]
Yes, the second one is debatable. _But I think it fits in the spirit of the GDPR still: only require the minimal needed data to complete the order._ It makes no sense why a admin needs to create a customer account to create a backend order, while a customer can place the order without it on the frontend.

Also, I think the implementation of this could be done pretty easily. I remember a thread where this was possible when some payment module was used, not sure which one it was though.

**Comment by thomas-kl1** [comment]
@SomeGeek I also thin that we should be able to create an order without creating a new customer (if guest is disabled). However this module is not the right place to achieve it.

This feature should be available for everyone without installing the gdpr stuff. That's why I think it should be an other module. Thanks to composer we can add it as a suggestion at the installation.

**Comment by SomeGeek** [comment]
Great. Do you have any plans to pick that up as well?

**Comment by thomas-kl1** [comment]
@SomeGeek Yes I'd like to achieve that, but I can't tell you when. I really want to release this module in a stable enough version.
