### ISSUE TITLE
[ENHANCEMENT] Move "Accept Cookie" to Storage

### ISSUE THREAD

**Issue by elisei** [opengento/magento2-gdpr#122]
## Description

 The "acceptance of cookies" is currently in session, which creates unwanted behavior, customer returns to the site and even being logged in, or even with persistence of their cart, needs to accept cookies again.
 
 Priority of the change:
 - [x] High
 - [ ] Medium
 - [ ] Low

**Which problem the feature would fix?**  
O comportamento para dos cookies

**Describe the solution as simple as possible**  
Move the cookie to local storage.

**Additional context**  
![image](https://user-images.githubusercontent.com/1786389/165858135-aeb3d931-bb09-4067-9bce-b629148967aa.png)
![image](https://user-images.githubusercontent.com/1786389/165858155-cf0aee6c-f76a-4a17-9754-66342705759e.png)

## Contributing

 - [x] Would you want to contribute and to be assigned to this enhancement?

**Comment by thomas-kl1** [comment]
Hi @elisei 

This comment might interest you: https://github.com/opengento/magento2-gdpr/issues/9#issuecomment-875500094
There's already a similar feature in Magento so we don't need the one provided by this module (as it only shows a disclosure and don't allow to consent to and configure stored cookies)

**Comment by elisei** [comment]
Hi @thomas-kl1 

I believe that the topic you mention is not quite what I propose, maybe the pull clarifies it better:
https://github.com/elisei/magento2-gdpr/pull/1/files

The main proposed changes are:
- Set visible to false. It will only be displayed if there is no cookie.
- Instead of setting the cookie to "session" I move it to local storage. This will make the once-dated authorization remain as authorized until the data is cleared. With this, the client returns to the site, after a period longer than the session, he is still authorized.

This last point aims to correct situations such as:
- Customer comes back to the site, the session time for account cookies has not yet expired, but we still ask for his authorization to record cookies! o.O Hours if I have not yet authorized cookies how am I still logged in?

**Comment by elisei** [comment]
PS. In Pull also add a check so that the popup is only visible if it is not a bot or lighthouse, thus avoiding loss in the CLS factor.

**Comment by thomas-kl1** [comment]
@elisei feel free to open a pull request
