### ISSUE TITLE
[BUG] export personal data from admin panel failed

### ISSUE THREAD

**Issue by AlbertoTorrisi** [opengento/magento2-gdpr#129]
## Description  
When I go to: customers -> all customers -> select a customers -> export personal data(after click confirm) this is the error:
An error has happened during application run. See exception log for details.:
attached log error
[error-export-data.txt](https://github.com/opengento/magento2-gdpr/files/9300913/error-export-data.txt)

## Prerequisites  

**PHP Version:**
7.4

**Magento Version:**
2.4.2-p2

**Module Version:**
2.4.3

**Comment by thomas-kl1** [comment]
Hi @AlbertoTorrisi, how did you installed the module? There's a dependence in composer?json that requires "tecnickcom/tcpdf": "^6.4",
It seems you didn't used composer to install the module.
Please use composer if possible it's better to manage dependencies and upgrades. If you can't, please install the missing dependencies.

**Comment by AlbertoTorrisi** [comment]
Thank you for the fast answer!
installed by composer works perfectly! :D :D
Really nice extension!
thank you again!
