### ISSUE TITLE
[BUG] No notifications on any user action

### ISSUE THREAD

**Issue by boter3** [opengento/magento2-gdpr#141]
## Description  
I am not getting any notifications (mails), no matter what settings, in Magento 2.

I believe it has something to do with 'core_config' setting paths that are declared in di.xml file for `gdpr/notification/xxxxxxx` paths, which shouldn't have so many sublevels.

So instead `gdpr/notification/export/ready/order/enabled` there should be `gdpr/notification/export_ready_order_enabled`.

```
    <virtualType name="Opengento\Gdpr\Model\Order\Export\Notifier\Ready\MailSender" 
       type="Opengento\Gdpr\Model\Order\Notifier\MailSender">
        <arguments>
            <argument name="configPaths" xsi:type="array">
                <item name="is_available" xsi:type="string">gdpr/notification/export/pending/customer/enabled</item>
                <item name="from" xsi:type="string">gdpr/notification/export/pending/customer/identity</item>
                <item name="copy_to" xsi:type="string">gdpr/notification/export/pending/customer/copy_to</item>
                <item name="copy_method" xsi:type="string">gdpr/notification/export/pending/customer/copy_method</item>
                <item name="template_identifier" xsi:type="string">gdpr/notification/export/pending/customer/template</item>
            </argument>
        </arguments>
    </virtualType>
```

Actual paths in table:

```
gdpr/notification/export_pending_copy_method
gdpr/notification/export_pending_copy_to
gdpr/notification/export_pending_enabled
gdpr/notification/export_pending_guest_template
gdpr/notification/export_pending_identity
gdpr/notification/export_pending_template
```

## Prerequisites  

**PHP Version:**
 - 8.1.27

**Magento Version:**
 - 2.4.5

**Module Version:**
 - 4.4.2

## Issue Details  

**Steps to reproduce the behavior**
1. Go to User Account > Privacy Settings > Export Personal Data (or any other action)
2. No notification is ever sent.

**Expected behavior**  
A notification should be sent to User mail + Admin mail, that is set in settings.

**Comment by thomas-kl1** [comment]
Fixed in 15fde18a28d9bbdab27be1e11b96f6c997f6fea9 , will be shipped in the release 5.0
