### ISSUE TITLE
Auto erase personal data after an inactive period

### ISSUE THREAD

**Issue by thomas-kl1** [opengento/magento2-gdpr#17]
Personal data of inactive users since at least 3 years must be erased.
This value should be configurable in the settings.

**Comment by SomeGeek** [comment]
How about sending the specified customer a reminder email prior to erasure?

**Comment by thomas-kl1** [comment]
Good point, should be done easilly

**Comment by thomas-kl1** [comment]
Hi @SomeGeek , notifications will be achieved in an another task (actually all actions must be notified to the customer).
