### ISSUE TITLE
Localisation: nl_NL

### ISSUE THREAD

**Issue by SomeGeek** [opengento/magento2-gdpr#21]
Will provide a Dutch i18n file later this weekend!

**Comment by thomas-kl1** [comment]
Thanks :) any help is welcomed! Please use the latest head of master and the i18n command line génératif, the current csv are out of date

**Comment by SomeGeek** [comment]
opengento/magento2-gdpr#22

**Comment by SomeGeek** [comment]
Just out of my curiosity: Why did you reopen this issue?

**Comment by thomas-kl1** [comment]
The translation file you provide does not contains all translations. The current files: fr_FR.csv and en_US.csv are not up-to-date.

Please use the following command to generate the correct translation file: 
`bin/magento i18n:collect-phrases`

See 4bc88e0addb56e35759a8b4199ec41f1c8d5a5e9 for the latest changes

**Comment by SomeGeek** [comment]
Will look into it. What is the best way to merge my current translations with the new ones?

**Comment by SomeGeek** [comment]
I updated the Dutch translations. I found some things tricky to translate, as some words don't have a direct Dutch equivalent. I did my best, though.

If someone with more 'law experience' knows better words or phrases, feel free to commit!

**Comment by thomas-kl1** [comment]
Thanks a lot @SomeGeek for your contributions :)

**Comment by thomas-kl1** [comment]
Translation are now available here:

https://www.transifex.com/opengento/opengentomagento2-gdpr/translate/#nl_NL/en_uscsv/188723379

**Comment by thomas-kl1** [comment]
Transferred to #55
