### ISSUE TITLE
Magento 2.3.2;  gdpr-module version 2.0.0-beta5

### ISSUE THREAD

**Issue by bst2002git** [opengento/magento2-gdpr#25]
PHP Fatal error:  Class Opengento\Gdpr\Console\Command\EraseCommand\Interceptor may not inherit from final class (Opengento\Gdpr\Console\Command\EraseCommand) in /usr4/data/web2124/web/generated/code/Opengento/Gdpr/Console/Command/EraseCommand/Interceptor.php on line 7

**Comment by thomas-kl1** [comment]
Hi, thanks for reporting this issue

It's related to this point:
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html#new-relic-reporting

The command classes should be final.

**Comment by bst2002git** [comment]
Ok, tnx, seems working!
