### ISSUE TITLE
[BUG] master: Email template 'gdpr_notification_export_succeeded_template' is not defined

### ISSUE THREAD

**Issue by VincentMarmiesse** [opengento/magento2-gdpr#34]
## Description  
The error message 
```
Email template 'gdpr_notification_export_succeeded_template' is not defined
```
is displayed when I try to go to the GDPR section in admin.

## Prerequisites  

**PHP Version:**
 - 7.2.15

**Magento Version:**
 - 2.3.1

**Module Version:**
 - master branch

## Issue Details  

**Steps to reproduce the behavior**
1. Go to `Stores > Configuration > Customers > GDPR Compliance`
2. See error

**Expected behavior**  
There is no error :)

**Comment by thomas-kl1** [comment]
Updated fix in bc06dc91f320b4ab97f4e1d89389e9f408451226
