### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bst2002git** [opengento/magento2-gdpr#36]
## Description  
main.CRITICAL: Type Error occurred when creating object: Opengento\Gdpr\Model\Config\Source\EraseComponents, Argument 2 passed to Opengento\Gdpr\Model\Config\Source\EraseComponents::__construct() must be of the type string, null given, called in /web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116 [] []
##
1 exception(s):
Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Opengento\Gdpr\Model\Config\Source\EraseComponents

Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Opengento\Gdpr\Model\Config\Source\EraseComponents
<pre>#1 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#2 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#3 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/BlockFactory.php:46]
#5 Magento\Framework\View\Element\BlockFactory->createBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:268]
#6 Magento\Framework\View\Layout\Generator\Block->getBlockInstance() called at [vendor/magento/framework/View/Layout/Generator/Block.php:248]
#7 Magento\Framework\View\Layout\Generator\Block->createBlock() called at [vendor/magento/framework/View/Layout.php:776]
#8 Magento\Framework\View\Layout->_createBlock() called at [vendor/magento/framework/View/Layout.php:759]
#9 Magento\Framework\View\Layout->createBlock() called at [vendor/opengento/module-gdpr/Block/Adminhtml/Config/Form/Field/EraseComponentsProcessors.php:37]
#10 Opengento\Gdpr\Block\Adminhtml\Config\Form\Field\EraseComponentsProcessors->getEraseComponentsSelectRenderer() called at [vendor/opengento/module-gdpr/Block/Adminhtml/Config/Form/Field/EraseComponentsProcessors.php:77]
#11 Opengento\Gdpr\Block\Adminhtml\Config\Form\Field\EraseComponentsProcessors->_prepareToRender() called at [vendor/magento/module-config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php:254]
## Prerequisites  

**PHP Version:**
PHP 7.2.14

**Magento Version:**
 2.3.3

**Module Version:**
dev-magento2.3.x

## Issue Details  

**Steps to reproduce the behavior**
1. Go to Admin-backend ->Stores->configuration->Customers->GDPR Compliance

**Comment by thomas-kl1** [comment]
Hi @bst2002git it should be fixed in 2feadce4f3c438ba9ad181ce6068264c5b4dff38
Be cautious, I've merged many new features into magento2.3, many BC breaks

**Comment by bst2002git** [comment]
Hello, i'l try it tomorrow...
