### ISSUE TITLE
[BUG] make package compatible with Magento 2.3.4

### ISSUE THREAD

**Issue by daumling** [opengento/magento2-gdpr#44]
## Description  
Please make the package compatible with Magento 2.3.4

## Prerequisites  

**PHP Version:**
 - 7.2.23

**Magento Version:**
 - 2.3.4

**Module Version:**
 - n/a

**Desktop (if applicable):**  
 - OS: MacOS
 - Browser chrome
 - Version 82

## Issue Details  

Error message:

Could not find a version of package opengento/module-gdpr matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by thomas-kl1** [comment]
Hi @daumling try with dev-master, however I can't guarantee that the module works perfectly.

**Comment by thomas-kl1** [comment]
Fixed in 64b3da1abab9cc1c3bd0924f348f4055c50e25fe v3.0.0-beta.2
