### ISSUE TITLE
[BUG] Less rules should be in mixin guards

### ISSUE THREAD

**Issue by antoniocarboni** [opengento/magento2-gdpr#53]
File less should have the structure of other Magento less files. The css directives should be inside the Magento mixin guards. As a consequence, as an error, the css rules are duplicated in the css files generated by magento.

**Comment by antoniocarboni** [comment]
sorry for the mess I'm not able to working directly on github :P

**Comment by thomas-kl1** [comment]
@antoniocarboni No problem, this is fine :smile:
