### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by thomas-kl1** [opengento/magento2-gdpr#55]
For the localisation of the project we are using https://www.transifex.com/opengento/opengentomagento2-gdpr/languages/.
Please translate the content directly on the transifex project. We have enabled the transifex integration and the dictionnary will be pushed when updated or 100% translated.

- [x] [English](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/en_US/)
- [x] [French](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/fr_FR/)
- [x] [Dutch](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/nl_NL/)
- [x] [German](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/de_DE/)
- [x] [Italian](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/it_IT/)

**Comment by template-provider** [comment]
Hi,
can you add the german translation for feature request? We will do this in the next days.

**Comment by thomas-kl1** [comment]
Hi @template-provider 

Thank you for joining us as a contributor :)
You can find the German translation project at: https://www.transifex.com/opengento/opengentomagento2-gdpr/language/de_DE/
Once it's translated you can download the csv and create the PR.

**Comment by lukawefocus** [comment]
@thomas-kl1 I've transalted the remaing phrases for nl_NL 
Can you add it to the project?
