### ISSUE TITLE
Missing support for custom and extension attributes of entities

### ISSUE THREAD

**Issue by thomas-kl1** [opengento/magento2-gdpr#7]
Add in export and anonymiser the capability to process custom and extension attributes (and add them to the configure list in system config).

**Comment by thomas-blackbird** [comment]
https://github.com/opengento/magento2-gdpr/commit/2a83bd568c739f7e8d7a73e14050f918d52697cb

**Comment by thomas-blackbird** [comment]
0c42f8c73bf836fb2c695a05cb4f24bd1bd35ee0

**Comment by thomas-kl1** [comment]
f8e1883b1bb83a50d4b9d50937ca03206319a5fc

**Comment by thomas-kl1** [comment]
08410dd88bfaf3bddc94988c58ad47d335107fab

7d7394a8a0afc26897038d762187cf21eccb7c9b

4eeedb2ec61c68651f26b0e7a15afb13ada19d92

**Comment by thomas-kl1** [comment]
fd20681d2f6dce9003ad139483cec2c1ef95d0f4

4fd46612fa7fb8886d0210bd99216cbc712ae24e

**Comment by thomas-kl1** [comment]
3d5c1ff90d9b945121093976aa5f8b37bbb6dba7

**Comment by thomas-kl1** [comment]
d4e2839b4799f064d56f8133b484d91adb3f13e6
