### ISSUE TITLE
Italian Localisation

### ISSUE THREAD

**Issue by thomas-kl1** [opengento/magento2-gdpr#75]
For the localisation of the project we are using https://www.transifex.com/opengento/opengentomagento2-gdpr/languages/.
Please translate the content directly on the transifex project. We have enabled the transifex integration and the dictionnary will be pushed when updated or 100% translated.

- [ ] [Italian](https://www.transifex.com/opengento/opengentomagento2-gdpr/language/it_IT/)

**Comment by antoniocarboni** [comment]
translation complete

**Comment by thomas-kl1** [comment]
thank you a lot for your contributions @antoniocarboni
