### ISSUE TITLE
[BUG] Popup in absolute position instead fixed position

### ISSUE THREAD

**Issue by antoniocarboni** [opengento/magento2-gdpr#81]
## Description  
Cookie Popup is printed inside page in many themes

## Prerequisites  

**PHP Version:**
 - [e.g. 7.2.19]

**Magento Version:**
 - [e.g. 2.3.2]

**Module Version:**
 - dev-master

**Desktop (if applicable):**  
- all

## Issue Details  

**Steps to reproduce the behavior**
1. Enable Popup.'

**Expected behavior**  
Popup should be in fixed position

**Comment by thomas-kl1** [comment]
thanks @antoniocarboni  🥇
