### ISSUE TITLE
[BUG] Issue compile on php7.4 magento 2.4.1

### ISSUE THREAD

**Issue by tuanhatay88** [opengento/magento2-gdpr#84]
Class Opengento\Gdpr\Block\Adminhtml\Customer\Edit\EraseButton\Interceptor may not inherit from final class (Opengento\Gdpr\Block\Adminhtml\Customer\Edit\EraseButton) in /home/cloudpanel/htdocs/glamira2.local/generated/code/Opengento/Gdpr/Block/Adminhtml/Customer/Edit/EraseButton/Interceptor.php on line 7
( removed final to fix )

**Comment by thomas-kl1** [comment]
Hi @tuanhatay88 are you trying to add a plugin to the class or interface? If yes for what purpose? The button class can be replaced in the ui componenet declaration schema.

If it's done by a third party components could you tell me which one?

**Comment by thomas-kl1** [comment]
@tuanhatay88 any updates?
