### ISSUE TITLE
[BUG]   PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Archive\ArchiveInterface

### ISSUE THREAD

**Issue by antoniocarboni** [opengento/magento2-gdpr#88]
## Description  
Error trying to compile with magento2-gdpr on dev-master:
  PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Fram  
  ework\Archive\ArchiveInterface

## Prerequisites  

**PHP Version:**
7.4

**Magento Version:**
2.4.1

**Module Version:**
dev-master

For now i solved it only downgrading magento2-gdrp to 4.0.*

**Comment by thomas-kl1** [comment]
Hi @antoniocarboni 
Thank you for reporting this issue!

This issue has been introduced by f3f5c6c5ae4941875fcec916c2061bb02ef6d45c in order to resolve an other issue, see #87 

Hope it's working better in this way!
