### ISSUE TITLE
Cannot instantiate interface Magento\Framework\Archive\ArchiveInterface

### ISSUE THREAD

**Issue by ydup788** [opengento/magento2-gdpr#89]
Bonjour @thomas-kl1,

Je relève un bug sur la dernière version quand on exécute un setup:upgrade sur un magento 2.4.1 : 

`[27-Apr-2021 08:53:20 UTC] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Archive\ArchiveInterface in /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'archive', 'Opengento\\Gdpr\\...')
#3 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Opengento\\Gdpr\\...', Array, Array)
#4 /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectMa in /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50`

**Comment by thomas-kl1** [comment]
@ydup788 It was already reported and fix as #88 but it seems it has never been released... I'm taking care of it!
Thanks for the report!

**Comment by thomas-kl1** [comment]
Released as 4.1.0

**Comment by ydup788** [comment]
@thomas-kl1 Thanks but the problem persists with Release 4.1.0

**Comment by thomas-kl1** [comment]
Yeah, I know why it was not released then.. My bad, It's fixed in 4.1.1
