### ISSUE TITLE
[BUG] composer constraint should be set to 2.3.5+

### ISSUE THREAD

**Issue by nesh** [opengento/magento2-gdpr#91]
## Description  

Current composer constraint allows installing extension on Magento versions prior 2.3.5.

## Prerequisites  

**PHP Version:**
 - 7.2.34

**Magento Version:**
 - 2.3.3-p1

**Module Version:**
 - 3.0.0

**Comment by thomas-kl1** [comment]
Hi @nesh sadly the composer constraint is wrong, my bad, the minimum version support is Magento 2.3.5. The SessionCleaner class have been introduced at 2.3.5 only.

**Comment by nesh** [comment]
Thanks,  you can close it or I can re-word it as composer constraint bug then.

**Comment by thomas-kl1** [comment]
@nesh yes please, reword the issue :)

**Comment by thomas-kl1** [comment]
Won't do, we are going to focus on Magento 2.4 now. Sorry for the pain!
