### ISSUE TITLE
[BUG] Event based on model modification

### ISSUE THREAD

**Issue by mageho** [opengento/magento2-gdpr#92]
## Description  
Since your last version 4.1.0, in developper mode of Magento, application debugging throwing error as :

> TypeError: Argument 1 passed to Opengento\Gdpr\Observer\DeleteExport::fetchExportEntities() must be an instance of Magento\Framework\Model\AbstractModel, null given, called in /home/amadeco/public_html/Future/vendor/opengento/module-gdpr/Observer/DeleteExport.php on line 72 and defined in /home/amadeco/public_html/Future/vendor/opengento/module-gdpr/Observer/DeleteExport.php:88

It seems event configured is launched even when no entity is declared.

I solved this for now by doing a checking condition in _vendor/opengento/module-gdpr/Observer/DeleteExport.php_ :  
Line 66, function execute : 

`
    public function execute(Observer $observer): void
    {
        /** @var AbstractModel $entity */
        $entity = $observer->getData('data_object');

        if ($entity instanceof AbstractModel) {
            try {
                foreach ($this->fetchExportEntities($entity)->getItems() as $exportEntity) {
                    $this->exportRepository->delete($exportEntity);
                }
            } catch (LocalizedException $e) {
                $this->logger->error($e->getLogMessage(), $e->getTrace());
            } catch (Exception $e) {
                $this->logger->error($e->getMessage(), $e->getTrace());
            }
        }
    }
`

## Prerequisites  

**PHP Version:**
> 7.3

**Magento Version:**
> 2.4.2

**Module Version:**
last version available
> 4.1.1

## Issue Details  

**Steps to reproduce the behavior**
It appears so far when you want to delete a product from cart but also in admin back-office, in products inventory catalog by example

**Screenshots**  
<img width="1325" alt="Capture d’écran 2021-05-08 à 19 34 21" src="https://user-images.githubusercontent.com/2975845/117548353-da2b7080-b034-11eb-9e0f-100ffb090b01.png">

**Comment by thomas-kl1** [comment]
Hi @mageho 
Thank you for reporting this issue! It has been fixed along 4.1.2
I've lowered the subtype to be DataObject, as we only use the getData method and we use the Magento built-in mechanism to retrieve the entity type.
