### ISSUE TITLE
Impossible to process the erasure: "Street Address" cannot contain more than 1 lines [BUG]

### ISSUE THREAD

**Issue by kunzi** [opengento/magento2-gdpr#93]
## Description  
Trying to erase customer data results an error:
Customer with id "9807": Impossible to process the erasure: "Street Address" cannot contain more than 1 lines.

## Prerequisites 
In the Magento settings there is only one line for street address set. Also ran this to force all addresses to one line:
update customer_address_entity set street = replace(street,'\n',','); 
It did not seem to help.

**PHP Version:**
7.4

**Magento Version:**
2.4.0

**Module Version:**
4.1.2

## Issue Details  

**Steps to reproduce the behavior**
1. Go to customer list in admin
2. Select customer
3. From actions select Erase (GDPR)
4. Error: Customer with id "9807": Impossible to process the erasure: "Street Address" cannot contain more than 1 lines.

**Expected behavior**  
Customer data is being erased.

**Comment by thomas-kl1** [comment]
Hi @kunzi it has been fixed in 4.1.3 release!
Thanks for reporting this case :)
