### ISSUE TITLE
Order anonymization does not seem to work [BUG]

### ISSUE THREAD

**Issue by kunzi** [opengento/magento2-gdpr#94]
## Description  
When customer erases his data the customer account's data seems to get anonymized, but data of his orders do not. All order data is like it was before.

## Prerequisites  

**PHP Version:**
7.4

**Magento Version:**
2.4.0

**Module Version:**
4.1.3

## Issue Details  

**Steps to reproduce the behavior**
1. Customer clicks the erase data button

**Expected behavior**  
After a while customer account data and order data should get anonymized as set in settings Customer Component Erasure Strategy and Order Attributes Anonymizers.

**Screenshots**  
![Screenshot at May 14th 2021 - 12 54 24 pm](https://user-images.githubusercontent.com/3381121/118255047-6fef5180-b4b4-11eb-843d-42d79ef25a05.png)
![Screenshot at May 14th 2021 - 12 54 41 pm](https://user-images.githubusercontent.com/3381121/118255051-72ea4200-b4b4-11eb-97e5-91f94b75ad74.png)
![Screenshot at May 14th 2021 - 1 03 35 pm](https://user-images.githubusercontent.com/3381121/118255343-d4121580-b4b4-11eb-9398-0bf1c5dafcb1.png)

**Comment by thomas-kl1** [comment]
Hi @kunzi 

I thinks it's related to this setting: https://github.com/opengento/magento2-gdpr/blob/master/etc/adminhtml/system/erasure.xml#L65

The order should be scheduled to be erased within a different delay. Sales information should be kept for financial receipts and documents.

**Comment by thomas-kl1** [comment]
@kunzi check the table `opengento_gdpr_erase_entity` there should be an entry for the order entity.

**Comment by kunzi** [comment]
@thomas-kl1 Thank you. I will check that. 

I'm not sure how the GDPR goes on order data erasing. Should all the order data be kept for tax officials etc. or is it enough to keep only the totals sums, taxes and what items were bought? In my country the receipts should be kept for 6 years, but not all receipts have for example customer's name (brick and mortar shop's receipts for example) so I'm guessing that the name is not something that is absolutely required to be kept and therefore GDPR's right to be forgotten might override the need to keep the name for example for taxing purposes.

But I'm no tax nor GDPR expert.

**Comment by kunzi** [comment]
I called the accountant. He was not 100% certain, but in his opinion if the sales data (sums and receipts) has been recorded in the accounting software that should be enough for tax officials and the web store's sales data is not something that should be kept for taxing purposes anymore and customer data could therefore be anonymized. 

That of course might transfer the problematic "right to be forgotten" to the accounting software and what data is essential to be kept there, but that is another matter.

**Comment by thomas-kl1** [comment]
Hi @kunzi thank your for the valuable information!
If you don't need to keep the sales information into Magento because you have a third party system, you can adjust the following setting `gdpr/erasure/sales_max_age`. This setting lives at Stores > Configuration > GDPR Compliance > Right To Erasure > Sales Information Lifetime

**Comment by thomas-kl1** [comment]
@kunzi I'm closing the issue, if you think it shouldn't, feel free to reopen it :) 

Hope this module helps you as much as possible.
