### ISSUE TITLE
I can't add different block for different store view

### ISSUE THREAD

**Issue by ibaritakis** [opengento/magento2-gdpr#95]
## Description  
I enable magento2-gdpr and I choose a block for Information. Works as expected.
Because my store is bilingual I want to choose an other block for the second language but I can not.
When I change store view the Information field disappears.

## Prerequisites  

**PHP Version:**
 - 7.3

**Magento Version:**
 - 2.4.1

**Module Version:**
 - latest

**Comment by thomas-kl1** [comment]
Hi @ibaritakis 

This fields depends of the "enabled" field. The only reason for the field to disappear would be that "Enabled" is set to "No".

**Comment by thomas-kl1** [comment]
@ibaritakis did I replied to your question?

**Comment by ibaritakis** [comment]
Yes, thanks a lot!

**Comment by thomas-kl1** [comment]
Might be related to #100

**Comment by thomas-kl1** [comment]
Fixed by ca79edfdc72558b70cb7a44bf62f1e305af9cbe7
