### ISSUE TITLE
[BUG] Getting error on attempt to download personal datas a second time

### ISSUE THREAD

**Issue by Oddrigue** [opengento/magento2-gdpr#97]
## Description
Receiving an error message after attempting to download personal datas a second time

## Prerequisites

**PHP Version:**
 PHP 7.3
 
**Magento Version:**
Magento Enterprise Edition 2.3.6

**Module Version:**
3.0.0

## Issue Details

**Steps to reproduce the behavior**
1. Request a personal data export
2. Whenever the personal data export is available, click on the link to download the archive a first time
3. Attempt a second time to download the personal datas by clicking the link again
4. The page reloads with the error message "Something went wrong, please try again later!" (screenshot in french)

**Expected behavior**
Expected to be able to download the archive file once again.

**Screenshots**
![image](https://user-images.githubusercontent.com/22291422/122353365-4496d100-cf50-11eb-8f1a-2f1abd6f6827.png)

**Comment by thomas-kl1** [comment]
Thank you for reporting this issue! I you could, upgrade to the latest major version, else the fix for 3.x should be released as soon as I have free time on my schedule (not so quickly sadly)

**Comment by thomas-kl1** [comment]
Won't do, we are going to focus on Magento 2.4 now. Sorry for the pain!
