### ISSUE TITLE
[BUG] Invalid return type when customer session expires

### ISSUE THREAD

**Issue by owebia** [opengento/magento2-gdpr#99]
## Description  
When the customer session expires, customer's privacy setting pages throw an "Invalid return type" exception.

## Prerequisites  

**PHP Version:**
 - 7.4.20

**Magento Version:**
 - 2.4.2

**Module Version:**
 - 4.1.3

**Desktop (if applicable):**  
 - OS: Windows
 - Browser chrome
 - Version 91.0.4472.114

## Issue Details  

**Steps to reproduce the behavior**
1. Connect to a customer account
2. Go to the privacy setting page
3. Wait for the customer's session to expire
4. Refresh the privacy setting page
5. See error

**Expected behavior**  
The page should redirect to the login page.

**Additional context**  

Exception thrown here:
https://github.com/magento/magento2/blob/2.4.2/lib/internal/Magento/Framework/App/Http.php#L124

Why the exception is thrown:  

`Magento\Customer\Controller\Plugin\Account` returns nothing when the session is not authenticated:
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Customer/Controller/Plugin/Account.php#L60-L66

The module's controllers are not inheriting `AbstractAction`, then `execute` is called instead of `dispatch`:
https://github.com/magento/magento2/blob/2.4.2/lib/internal/Magento/Framework/App/FrontController.php#L185-L189

`Magento\Framework\App\Action\Action` returns the response when the result is empty:
https://github.com/magento/magento2/blob/2.4.2/lib/internal/Magento/Framework/App/Action/Action.php#L115

**Comment by thomas-kl1** [comment]
Thank you @owebia for reporting this issue! It should be resolved soon :)

**Comment by thomas-kl1** [comment]
That's actually a nice Magento bug, once again.. Good catch! If we want to use the AccountInterface we need to extends the default AbstractAction from Magento Framework.. I'm going to use a workaround
